language: node_js
node_js:
- '0.12'
script:
- npm test
notifications:
  slack:
    rooms:
      secure: o/eg7lWsX5qAgjNLKik2krQZcA9TsYx2iw3865IhJY4AaikNNmo5ZE8amARvF8Z4ZtAeAZGlL+KHKMQTFN2o3ZdyStJw55rhjzaYHEREBuyUi95VLjKcM8Znhe5/6iTYwLpi/eC6zMbYKTJsLC9cOrKkf637OUuLhaQntC2RtVH2s7tmGYl+LZgrJ4quSw3WuvSlMXXPTD803mzuLJzjie7KJKrcHpWBzH9DVhBdwqfsngZPBRdCfsuoRgxuXr2AMbWRHXJ5sxaFdt2SNIiKrDwzg4wGDdE0mlAHMQpiWgQg0KIwMPHQMcM9lvyJLEUNXj8BuY4PXuAqYeotxDF/b39zwcY4+yj6MLNNP/Sw1O4AL6s14IYIpI1KbVwBccBNKijjIMvqtdMcRJCAYqvoD4adkXnbJCAT48hSSsUUrqWhr/2O8ieSsNXtBnOHpvITwiA8avtqeVq0nugOwqtvAWwhgATYxCSd+4ToRQx1ttF8z+xzaek7UzqIliG5UTR6bN/xgxKzRtvrUkpsl05AF+Fl9RimW0ccqURMXmG5HiYON8g85LzBGeZp4cwSgekTKEc7CJsrltZ32rl+3JxxfaZ95sZwLdhJgDl7C6tIQlKuLzaZvEcikjbY7TCbdFh6oegqUj/ssY0SQIK4JokjdKJaYfFmxtQ+eoGmWl6LDlk=
    on_success: change
    on_failure: always
